### ISSUE TITLE
Suggestion and issue need to fix, add

### ISSUE THREAD

**Issue by tungdo0602** [SebOuellette/LiveBot#139]
Can you add some feature like:
use emoji, animate emoji
open user dm
better mention user

cuz my account get disable LMAO :(

Some issue:
berry bot not working
chat bar broken

**Comment by SebOuellette** [comment]
Also, please don't have completely seperate ideas in one GitHub issue. Suggestions should be put in the Discord server anyway, so I'm going to just help with your issue in this thread, and close it when that is solved. 

First, I'm aware Barry is broken. It's going to take me some time to fix because of school and my job. 

Second, what about the chat bar is broken?

**Comment by tungdo0602** [comment]
> @tungdo0602 Maybe provide a bit more information than "chat bar broken"?

Like the chat bar is moving and not fit with the ui
