### ISSUE TITLE
Nothing showing

### ISSUE THREAD

**Issue by creepereldin** [SebOuellette/LiveBot#157]
Hello! When I log on to LiveBot, no servers or DM'S show, how can I fix it?

**Comment by SebOuellette** [comment]
-- Faq #1 --
Q: Why aren't some servers showing up?

A: 
Due to Discord privacy agreements, LiveBot can only show servers that both the bot and the owner are in, if even those servers aren't appearing, continue to the answer
Make sure that all the gateway intents are enabled. Due to new discord caching rules, these will need to be enabled for LiveBot to check if the owner is actually in that server, and read messages.

NOTE: THIS CAN SOMETIMES TAKE UP TO AN HOUR TO TAKE EFFECT
<img src="https://images.soue.ca/sYnPXRRHNN.png"/>

**Comment by asdat3** [comment]
note: with THE OWNER is not the Server owner ment, it is ment the owner of the bot (bot creator)
