### ISSUE TITLE
can't see any servers or DM's

### ISSUE THREAD

**Issue by ChilliTheDog** [SebOuellette/LiveBot#164]
- Branch/Release: Latest

#### Errors
![image](https://user-images.githubusercontent.com/96028524/151925473-5198ad63-6899-42b0-80a2-c3eaf01d3599.png)

#### Steps required to reproduce the bug
- Steps:
Logged in with the token and just shows the screen in screenshot

- Screenshot:
![image](https://user-images.githubusercontent.com/96028524/151925514-03acaea4-5853-4c95-a8fe-9c9dacc9c89c.png)

#### Description
I used Windows

**Comment by SebOuellette** [comment]
**Due to Discord privacy agreements, LiveBot can only show servers that both the bot and the owner are in, if even those servers aren't appearing, continue to the answer**

Make sure that all the gateway intents are enabled. Due to new discord caching rules, these will need to be enabled for LiveBot to check if the owner is actually in that server, and read messages.

**NOTE: THIS CAN SOMETIMES TAKE UP TO AN HOUR TO TAKE EFFECT**
<img src="https://images.soue.ca/sYnPXRRHNN.png"/>
