### ISSUE TITLE
Unstable; really hard to operate

### ISSUE THREAD

**Issue by Herobrine8761** [SebOuellette/LiveBot#216]
Dear Developer,
I have to inform you that your Application is really buggy and unstable. Most of the functions aren't working and none of the servers are visible in the application. Please work on this error. Thank you.

Regards,
Karti_Gamer YouTube.

**Comment by SebOuellette** [comment]
Dear, @Herobrine8761 
I have to inform you that your feedback has not helped me or the community to develop this application further. In my perspective, I have added the features I have intended to, and have added endpoints for users to add new features since I knew I would not be able to work on this full time, as I am also a student. 

Please work on your bug reporting skills, specifically by following the template we have provided. 

Regards,
A busy dev

**Comment by Herobrine8761** [comment]
Dear A busy dev,
I know I have poor bug reporting skills as I've never faced any bugs in any other projects and if any problems are faced they are fixed almost immediately with no complaints about my bug reporting skill issues. If you didn't understand what I meant by this issue I've opened, please tag me again. Thank you.

Regards,
Busy Minecraft Mod Creator.

_And by the way, please improve your grammar. I've noticed a few errors. Thanks :)_

**Comment by SebOuellette** [comment]
Ok so I'm not going to be passive aggressive anymore since you're just being a dick now. 

This is my repo, don't come in here with that bullshit after writing an issue like that. Follow the template, or I don't want to hear it.
