### ISSUE TITLE
Issue name goes here

### ISSUE THREAD

**Issue by noth874** [SebOuellette/LiveBot#252]
#### What branch/release are you using?

- Branch/Release:131

#### Errors
Cannout install the app

#### Steps required to reproduce the bug

- Steps:Nothing

#### Screenshot (In most cases required)

- Screenshot:Screenshot.png

#### Description
ITS not working

No

**Comment by SebOuellette** [comment]
Let's play a game. Using the information you gave me in this issue (since you barely provided any), let's solve it.

If it didn't install and you're on source, follow the instructions in the readme. If it didn't work and you're using the build, follow the instructions in the readme. 

If you are still having an issue, create a NEW issue amd actually fill out the template; provide screenshots, set the issue name, etc
