### ISSUE TITLE
Mobile Support

### ISSUE THREAD

**Issue by GhostieSpook** [SebOuellette/LiveBot#35]
I cant help but think how cool it would be to have this on my phone for when I'm away from home or something. I know it might be a bit hard to do but it would be a cool idea.

**Comment by hokkqido** [comment]
This could only be done if it was written entirely web based, though I'm also not sure how Electrom deals with phone apps

**Comment by dcrime** [comment]
That's not all
- the token storage is in a fixed position which means for the phone it'd need another way of managing the tokens
- the whole layout would have to be re-designed because as it is currently it wouldn't fit everything on the phone, that's why the official discord (phone) has menus that slide from the sides. You can test it by going on https://discordapp.com/ on the phone, not everything will be in the display
- it would be easier to just ditch this project and start from scratch with an actual program for making phone apps

**Comment by GhostieSpook** [comment]
True true. It may be easier to just do that and it would still be a really cool idea. Especially when I'm not at my PC 24/7.

**Comment by SebOuellette** [comment]
I'll keep it in mind!

**Comment by TheFinalDawn** [comment]
Yes, please do this, I want to prank my friends when they think I'm not at the computer.

**Comment by dcrime** [comment]
Remembered this thread, you can't run it natively but for android you can download termux, install linux on it and then install it like it would be normally on the os, was done by one of the server members

**Comment by SebOuellette** [comment]
The decision has been made that Mobile Support will not be added for livebot. Maybe once we create a website but that likely won't happen either.
