### ISSUE TITLE
Issue launching Livebot through the master branch.

### ISSUE THREAD

**Issue by vinnievega11** [SebOuellette/LiveBot#75]
Whenever I launch it, it gets stuck loading with the loading screen saying "There was an error while logging into the bot". When I checked in the console to see what the issue is it said "Invalid Token". The weird thing is I've never been able to actually launch the application so at no point would I have been able to put in a token. The image below shows the error. Edit: Forgot to mention the fact that using the electron build has the same result.
![6f1170f9e583a152006dedfe26fc5a86](https://user-images.githubusercontent.com/10425510/90298420-3a073900-de60-11ea-937f-2766670c6b19.png)

**Comment by SebOuellette** [comment]
Hi, I'm working out a fix for this issue, but basically the problem is an incorrect token. The fact that you have never been able to launch is weird... but we've had somebody with this issue where an incorrect token was the issue. 

So your steps to fix it, open the console in that inspect element window, and type `localStorage.removeItem('livebot-token')`, then press ctrl+r to reload, or restart livebot.

**Comment by vinnievega11** [comment]
Thanks. that fixed the issue. What's weird is even reinstalling it didn't fix the issue but thanks for the help.

**Comment by SebOuellette** [comment]
Localstorage is saved elsewhere on your machine, so reinstalling won't fix it. Either way, this bug shouldn't happen anymore since I fixed it in the latest commit.
