### ISSUE TITLE
A kinder attitude would be nice :)

### ISSUE THREAD

**Issue by Splatterxl** [SebOuellette/LiveBot#94]
I have been looking at this Project with awe for a while now, and since a couple of weeks ago, I've noticed a bad aura/attitude. 

- I comment some good, constructive criticism and it gets deleted. 
- One of the biggest contributors, @dcrime, has been banned from the Discord server.
- A potential good contributor has been
  - *1.* banned from the Discord Server,
  - *2.* flat-out rejected.

At this point, it's a matter of time before this issue is closed.

For anyone looking at this text, do not sponsor this Project until you are pretty certain you agree with its beliefs.

If this conversation is locked and closed, then it stands to reason that I'm correct.

**Comment by SebOuellette** [comment]
I would have rathered talk to you in private on discord about this, but you have me blocked so fine I will do it in public. 

I appologize about the bad attitude, it mostly stems from the fact that you and another person are berating me in public, while you can easily DM me on discord and I can explain my reasoning. I would rather not have all this in the public's viewing. 

About dcrime, he was banned and completely erased from the project because of multiple counts of sexual harassment to a minor. If you would like to argue that sending unsolicited nude photos to minors is not a big deal, then you can go right ahead. 

That "good contributer" was removed from the server for constantly telling me how to do my job, and to change my formatting that has been used for all my projects. It's not even incorrect in any sense. His PR was unstable, hence why he had to constantly undo certain commits because they caused issues. If most or all of his commits are causing issues, I don't even want to consider what else will cause issues. 

I will not be locking this conversation, or closing it (for now), so please, voice your comments and we can sort this out in public, or unblock me on discord and we can sort this out in private.

**Comment by Splatterxl** [comment]
I also want to apologise.

After banning me, you blocked me, so I thought you would keep it that way.

I did not know Daniel sent nude photos.

I am sorry.

**Comment by Splatterxl** [comment]
I also have no record in the Discord app of having blocked you. You seem to have blocked me.

**Comment by SebOuellette** [comment]
I tried to talk about this earlier with you and it said you blocked me. I don't have you blocked so I don't know what the issue would be. Anyways thank you for apologising, and I'm sure you can see now why I wanted to keep this private. 

Just let this be a lesson that people have their reasons. I tried to just clear dcrime's name quietly, as if he was never here, but some people including you got involved when it wasn't necessary.

**Comment by dcrime** [comment]
Well, since it's in public, perhaps you should be more honest about what happened, don't you agree?
I'll quickly go over it since it's really dumb
I wasn't completely erased as it can be seen in the server, as you know, I'm still in contact with some from the server and I did get some messages forwarded to me, like the login issue being copy pasted word by word from me, etc.. There's still stuff in the code too

**multiple counts of sexual harassment to a minor** and **unsolicited nude photos to minors**
First I'll just go and say this, I did send @SebOuellette a picture of my body which didn't contain any private parts, but it did contain my stomach and yes even my nipples (Which from what I know, I'm a guy? So nipples shouldn't be a problem?), the point here is that he's making it seem like it was something way worse than it was, at first he said "idk" which yeah, I agree that I shouldn't have done it no matter what the reasoning was (His opinion on how I look like), yes it is personal, but it doesn't hurt to say he's bi and he's sent quite a lot of sexual messages to me which were jokes, and I did send him messages like that too, tho that proves he was more than fine with messages, so harassment can't be called on this.
He said no while I was on my phone removing anything that could have even made it have a sexual view on it, yes, I actually edited the photo because I wanted his opinion, not to send him a "sexual picture", so by the time I was done, 0 notifications and I sent it, after a bit of talking, he said he didn't want me to and I looked back and saw that he said not to send it, the image was already deleted by his request (he said he didn't look at it either, so that might have to do with misinformation on the type of image it was), I was banned the next day and he's spread to others that I sent him a "d pic", yes, he said that, there wasn't one in the picture though, but the lies went ahead and he didn't want to even think about the whole thing an give the right information, but instead lies

I hope it wasn't too messy since I just woke up and that it cleared some things up

About the project, he said numerous times how he doesn't want to work on it, and how he isn't, the project is not being maintained as often as it should and it's not for the lack of time  or anything like that, but the sheer fact that he doesn't want to (it was the same with me), after I saw the donation link, I flipped because it's not going to the project, but it's going to go to games and no motivation will be gotten from this.
The attitude on these places and the server from him are awful, people are being judged the second they say something and rather than explaining anything like "I don't want you to do that because this and that" it's straight out rejected and mocked, it can be seen on multiple PR's on this project and going into the server would show the same thing if the messages aren't deleted!

All in all, spreading misinformation and just being plain rude ain't nice SF
