### ISSUE TITLE
[SUGGESTION] Discord Server?

### ISSUE THREAD

**Issue by DrMxrcy** [SebOuellette/LiveBot#97]
What happened to the discord server?

**Comment by SebOuellette** [comment]
Hey thanks for making this issue.

So basically, I had a discord bot that was owned by myself and an old team member who was fired. This team member has been making my life a living hell recently, this is their next big thing. It was completely my fault for forgetting to remove him from the team.

Now I'm working on setting up a new server, since the current one would literally take days to fix. I'll post the invite link here as soon as it's up.

I'm really sorry about all of this :/

**Comment by maalos** [comment]
lol

**Comment by SebOuellette** [comment]
AH yes thanks for reminding me maalos, here's the new link https://discord.gg/NG4rgqSgzx

Pretty rude of you to do this btw maalos

**Comment by maalos** [comment]
you got what you deserved for these lies.

**Comment by SebOuellette** [comment]
I didn't lie about anything lol

**Comment by maalos** [comment]
and the nude? he took his time to censor his pp and didnt see the msgs from u

**Comment by maalos** [comment]
i mean its over anyways

**Comment by maalos** [comment]
wow, got banned immediately

**Comment by SebOuellette** [comment]
He sent me one, I told him no, after I told him to delete it he said he thought it was funny. I don't see how I'm the bad guy here, but whatever. Yes obviously you got banned immediately lol, what did you expect?

**Comment by maalos** [comment]
there literally was nothing visible sooo


idc i can join the discord with my alt any moment

**Comment by SebOuellette** [comment]
You're right, yes you can. I don't see why you'd want to, but you do you. Anyways I'm ending this convo
